# Generated by Django 3.0 on 2020-11-27 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Ф.И.О.')),
                ('gender', models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина')], default='male', max_length=50, verbose_name='Пол')),
                ('room', models.IntegerField(verbose_name='Номер Комнаты')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='UserServiceEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service1_rank', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, verbose_name='Доброжелательность и оперативность персонала')),
                ('service2_rank', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, verbose_name='Обслуживание в  ресторане и разнообразие блюд')),
                ('service3_rank', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, verbose_name='Чистота и  оборудование номера')),
                ('service4_rank', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, verbose_name='Летний бар и бассейн')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='отзыв')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wellmax.UserInfo')),
            ],
        ),
    ]
