# Generated by Django 3.0 on 2020-11-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellmax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='unique_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
