# Generated by Django 3.0 on 2020-12-30 10:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreeHeightReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_0_0_2_count', models.FloatField(blank=True, null=True, verbose_name='0,2 м гача')),
                ('height_0_2_5_count', models.FloatField(blank=True, null=True, verbose_name='0,2 дан 0,5 м гача')),
                ('height_0_5_1_count', models.FloatField(blank=True, null=True, verbose_name='0,5 -1 м. гача')),
                ('height_1_1_5_count', models.FloatField(blank=True, null=True, verbose_name='1-1,5 м гача')),
                ('height_1_5_2_count', models.FloatField(blank=True, null=True, verbose_name='1,5-2 м гача')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.Department')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.Region')),
                ('tree_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.TreePlan')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_region', to='trees.Region'),
        ),
    ]
