# Generated by Django 3.0 on 2020-12-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
            ],
        ),
    ]
